
services:
  postgres-db:
    image: postgres:15-alpine
    container_name: postgres_container
    environment:
      POSTGRES_USER: gontran
      POSTGRES_PASSWORD: gontran123
      POSTGRES_DB: gestion_salon
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: