spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gestion_salon
    username: gontran
    password: gontran123

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  sql:
    init:
      mode: always

  defer-datasource-initialization: true

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

app:
  frontend-url: http://localhost:5173
  base-url: http://localhost:8080

springdoc:
  api-docs:
    enabled: true

  swagger-ui:
    enabled: true