spring:
  application:
    name: gestionSalon

  profiles:
    active: dev

server:
  port: 8080

application:
  security:
    jwt:
      expiration: 86400000
      refresh-token-expiration: 604800000